#include "pCh.h"
#include "framework.h"
//#include "stdafx.h"
#include "PathFinder.h"

#include "PathFinderDoc.h"
#include "PathFinderView.h"
#include "GetDestination.h"

char *HTMLPart1 = 
"<html> <head>  <meta content=\"text/html; charset=ISO-8859-1\" http-equiv=\"content-type\"> <title>";
char *HTMLPart2 =   "</title></head>\n<body> <font size=\"6\" color=\"#1346d4\"> <b>";
char *HTMLPart3 = "</b> </font> <table style=\"text-align: left;\" border=\"5\" cellpadding=\"1\" cellspacing=\"0\" BORDERCOLOR=#00166e>";

char *HeaderRow = "<thead align=center><th>Hop</th><th>IP Address</th><th>Name</th> <th>RTT</th><th>ISP/Organization</th><th>County</th></thead>\n<tbody>";
char *StartRow = "<tr>";
char *EndRow = "</tr>";
char *RowDataStart = "<td> ";
char *RowDataEnd = "<br></td> \n";

char *HTMLEnd = " </tbody></table><br> Generated by PathFinder <br> Get PathFinder from <a href=\"https://github.com/landkruzer/PathFinder\"> GitHub </a> </body></html>";


void CPathFinderView::OnFileSaveAs() 
{
	// TODO: Add your command handler code here
CString strFileName, strTitleBuf;
char *pszFileName, szItemText[256];
CPathFinderApp *pApp;
FILE *fp;
int nListCount;
int i, j;
char szFullFileName[512];

	CListCtrl& ListCtrl = GetListCtrl();

	nListCount = ListCtrl.GetItemCount();
	if( nListCount == 0 ) 
	{
		AfxMessageBox("Table empty");
		return;
	}


	pApp = (CPathFinderApp*) AfxGetApp();
	pApp->m_pMainWnd->GetWindowText(strTitleBuf);

	
	CFileDialog *pGetFile = new CFileDialog(FALSE, NULL, NULL, OFN_OVERWRITEPROMPT, _T("HTML Files (*.htm)"), this);

	if(pGetFile->DoModal() == IDOK)
	{


		//AfxMessageBox(pGetFile->GetPathName());
		strFileName = pGetFile->GetPathName();
		
		//pszFileName = strFileName.GetBuffer(256);
		//AfxMessageBox(strFileName);

		lstrcpy(szFullFileName, strFileName);
		lstrcat(szFullFileName, ".htm");
		//AfxMessageBox(szFullFileName);

		fp = fopen(szFullFileName, "w");
		if(fp == NULL) 
		{
			AfxMessageBox("Cannot create file");
		}
		else
		{



			fputs(HTMLPart1, fp);
			
			char *pszTemp = strTitleBuf.GetBuffer(256);
			fputs(pszTemp, fp);
			strTitleBuf.ReleaseBuffer();

			fputs(HTMLPart2, fp);
			fputs(pszTemp, fp);
			strTitleBuf.ReleaseBuffer();
				
			fputs(HTMLPart3, fp);

			fputs(HeaderRow, fp);

			for(i=0; i < nListCount; i++)
			{
				fputs(StartRow, fp);
				for(j=0; j < 6; j++)
				{
					fputs(RowDataStart, fp);
					ListCtrl.GetItemText(i, j, szItemText, 256);
					fputs(szItemText, fp);
					fputs(RowDataEnd, fp);
				}
				fputs(EndRow, fp);
			}
			fputs(HTMLEnd, fp);
		}	
		fclose(fp);
		strFileName.ReleaseBuffer();
	}
	delete pGetFile;
}
